---
title: "Escena del personaje"
date: 2026-06-23
date-modified: 2026-06-23
categories: [GameDev, Metroidvania, Godot]
draft: true
---

## Creando un escenario de pruebas

Primero crearemos un escenario básico que permita realizar pruebas con el personaje principal. Para ello, abrimos nuestra única escena (viniendo de la primera entrada) que se llama `stage.tscn` y seleccionamos `Stage` para agregarle un nodo hijo `Sprite2D`, al cual llamaremos `Ground` y le asignaremos una textura del tipo *GradientTexture2D* (en la opción *Texture -> Vacío*) al cual le daremos clic en el recuadro degradado que aparecerá y luego cambiaremos *Gradient* a un color sólido mediante la manipulación del rectángulo del extremo izquierdo. En mi caso lo dejaré de color negro. Enseguida, tanto en *Width* como en *Height* lo modificamos a `32`.

A nuestro `Sprite2D` le vamos a añadir un nodo `StaticBody2D` y a este último le agregamos su respectiva forma de colisión `CollisionShape2D`. Esta forma la redimensionamos para que cubra por completo nuestro sprite. Lo siguiente es cambiar el tamaño y forma del sprite para que ocupe toda la parte inferior de la pantalla, simulando un suelo. Para ello seleccionamos el nodo `Ground` y lo editamos en cuanto a tamaño y posición.

## Creando al personaje

Toca construir la estructura de archivos para nuestro personaje principal. Debido a que será una escena compuesta por estados, scripts, audio y animaciones, esta vez crearemos una carpeta dedicada únicamente al personaje. Creamos dicha carpeta con el nombre de `player` y dentro de ella agregamos otras que se llamarán `audio`, `scripts`, `sprites` y `states`.

Lo siguiente es crear una escena con nodo raíz del tipo `CharacterBody2D` que renombramos como `Player` y la llamaremos `player.tscn` y la guardaremos dentro de la carpeta homónima. Le asignaremos un nodo `Sprite2D` con una textura del tipo `PlaceholderTexture2D`. Quizá nos parezca demasiado pequeña, ya que es de apenas un píxel de alto y ancho, así que podemos modificar su tamaño a uno que resulte coherente con nuestra cuadrícula. Le pondŕe valores de `48` de alto por `16` de ancho. Es importante mencionar que resulta adecuado que el pivote del sprite quede justo en el extremo inferior del mismo y no en su centro. Para ello, seleccionamos dicho sprite y en la propiedad *Offset -> Y* la dejamos en `-24`. Enseguida agregamos el nodo de forma de colisión como hijo de `Player` y modificamos para que cubra por completo al sprite. Guardamos y seleccionamos la escena `ground.tscn` e instanciamos como su hija a `player.tscn`.

Seleccionamos la escena del personaje y agregamos un script al nodo raíz. Nos aseguramos de guardarlo en la carpeta `scripts` que creamos para el jugador. Si dejamos la plantilla que viene por defecto, el código estará casi listo, pero realizaremos algunos cambios para tener mayor control. En sí, el código quedará como sigue:

```gdscript
class_name Player extends CharacterBody2D

@export var SPEED = 300.0
@export var JUMP_VELOCITY = -400.0

func _physics_process(delta: float) -> void:
	# Agregar gravedad
	if not is_on_floor():
		velocity += get_gravity() * delta

	# Manejar el salto
	if Input.is_action_just_pressed("salto") and is_on_floor():
		velocity.y = JUMP_VELOCITY

	# Mover al jugador
	velocity.x = 0

	if Input.is_action_pressed("izquierda"):
		velocity.x = -SPEED
	elif Input.is_action_pressed("derecha"):
		velocity.x = SPEED

	move_and_slide()
```

Este script será modificado posteriormente. Por ahora funciona en cuanto a lo básico y además, creamos una clase llamada `Player` que estaremos utilizando más delante. Sin embargo, debemos crear una máquina de estados para el jugador.

## Máquina de estados para el personaje

Recordemos que creamos un conjunto de carpetas dentro de la propia del `player`. Dentro de la que llamamos `states` creamos un script que llamaremos `player_state.gd`. Lo primordial es crear otra clase ahí con la siguiente modificación a la primera línea y dos variables que representarán las dos clases en sí:

```gdscript
class_name PlayerState extends Node

# Creamos variable player
var player : Player

# Creamos variable del siguiente estado
var next_state : PlayerState
```

Luego crearemos una región donde pondremos las referencias a otros estados y enseguida, crearemos unas cuantas funciones que definirán qué sucederá cuando el estado actual se inicie, cuando entremos y también cuando salgamos de él. Entonces agregamos:

```gdscript
#region /// state references
# Referencias a otros estados
#endregion

# Evento cuando el estado inicia
func init() -> void:
	pass

# Evento cuando se entra al estado
func enter() -> void:
	pass

# Evento cuando se sale del estado
func exit() -> void:
	pass

# Manejo de entradas
func handle_inputs() -> PlayerState:
	return next_state
```

Dentro de las funciones que genera automáticamente Godot hay una llamada `_process()`. La vamos a editar para hacerla similar a la que va a estar manejando las entradas del jugador, además de agregar la función `_physics_process()`:

```gdscript
# Lo que pasa cuando la función coincide con el estado
func process(_delta: float) -> PlayerState:
	return next_state

# Lo que pasa cuando la función coincide con el estado
func physics_process(_delta: float) -> PlayerState:
	return next_state
```



